before_install:
- gem install -q sass
- gem install -q compass
- npm install -g -q bower
- npm install -g -q coffee-script
- npm install -g -q grunt-cli
- npm install -g -q protractor
install:
- npm install -q
language: node_js
node_js:
- '0.10'
addons:
  sauce_connect: true
env:
  global:
  - secure: VDfdfuwQOhY8I6klcqbK3sBVOYFCeVsW3AjbJZ+qgt64dI6JZlwGfg5xMHgHElXmGvlwBS/QVR5c+tHQUm1OwRxTKQzqESJvaPA7DLhPM7YEPNYEAmTajL23/imqJpKdJ2s/GkLQ+K/1oTB2P2WBaEoH7rYT4pJVcwxn1vw70/g=
  - secure: I9wj8jxxt1A2/iZJ0OhXucsqEf8/JnQNktlgBFogJZEXGsAz4l/S1/jWSa2oM0lpfTa7G5p4SXbV+nbM5vs1w2ry9Q8jsbPbSZYN8klsIVPuhnSzPhCuOO6evkBQOt5DcnFzPh33qRCnQBrKMB8qOjuh94qFHiTNM7NFTu56Sq4=
