before_install:
- gem install sass
- gem install compass
- npm install -g bower
- npm install -g coffee-script
- npm install -g grunt-cli
- npm install -g protractor
install:
- npm install -d
language: node_js
node_js:
- '0.10'
addons:
  sauce_connect: true
env:
  global:
  - secure: XNGijrA8aJI4BYcNGgWY1+337H8OosFOaV/QFSO27ZiPAM2hEM6IL1tgL+kHNCepiOwfTdpwpLKgDBV8uwu0FIIF1k0La8pJ32XCJw6WENZ4iwUiuEsCgiZIC4TJENFqlELxK+9RLb6lr9XcqnFLlBm21h78oU6iocp7RCIQZWs=
  - secure: MncVLRH0Res38Hir8UbRqu1p3Frcp/sltXEPCsAoX+XYKM1gA/j+zoYfxLXyWB/3EkUX6J+rlCzGK59lEbygjP66AnqImJ5xds7lW5LLfrHlGFxOe1+Lsp9Z7FMT+Q64bloNqq87sC2uoqVLdBlU+kKYF25zvFEoOQohiwyqWN0=
